### ISSUE TITLE
/jail cmd

### ISSUE THREAD

**Issue by AnshdeepS** [LVPYassine/Stunt-Freeroam-Gamemode#10]
after jailing a player we tele to jail but open jail We need jail like no body can go from room or like we can make cool jail in sea or sky

**Comment by AnshdeepS** [comment]
We have weaps to in jail

**Comment by AnshdeepS** [comment]
i jail my self for 2 minute but didnt get unjai automatically

**Comment by LVPYassine** [comment]
about jail, this one is better, because of the all bad players will get teleported to this room, so it will be amazing :p

**Comment by LVPYassine** [comment]
Fixed. Added.
